// <auto-generated />
namespace MiAplicacionApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_Animal_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_Animal_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201608100815372_create_Animal_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
